# Generated by Django 4.1 on 2023-04-14 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_usuario_partida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=50, unique=True)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estudianteID', models.AutoField(primary_key=True, serialize=False)),
                ('numeroLista', models.IntegerField(unique=True)),
                ('grupo', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('juegoID', models.AutoField(primary_key=True, serialize=False)),
                ('mundo', models.IntegerField()),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('intentoID', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('tiempoJugado', models.FloatField()),
                ('completado', models.BooleanField()),
                ('estudianteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.estudiante')),
                ('juegoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.juego')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='avanceJuegoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.juego'),
        ),
    ]
