# Generated by Django 4.1 on 2023-04-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadora", "0005_admin_estudiante_juego_intentos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante", name="grupo", field=models.CharField(max_length=2),
        ),
    ]
