# Generated by Django 4.1 on 2023-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculadora", "0006_alter_estudiante_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante", name="numeroLista", field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="estudiante", unique_together={("numeroLista", "grupo")},
        ),
    ]
