# Generated by Django 4.1 on 2023-04-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculadora", "0007_alter_estudiante_numerolista_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Admin",),
    ]
